In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

In [ ]:
!unzip /content/drive/MyDrive/dataset2.zip

Archive:  /content/drive/MyDrive/dataset2.zip
   creating: dataset/test/
   creating: dataset/test/authentic/
  inflating: dataset/test/authentic/Au_ani_0026.jpg  
  inflating: dataset/test/authentic/Au_ani_0027.jpg  
  inflating: dataset/test/authentic/Au_ani_0028.jpg  
  inflating: dataset/test/authentic/Au_ani_0029.jpg  
  inflating: dataset/test/authentic/Au_ani_0030.jpg  
  inflating: dataset/test/authentic/Au_ani_0031.jpg  
  inflating: dataset/test/authentic/Au_ani_0032.jpg  
  inflating: dataset/test/authentic/Au_ani_0033.jpg  
  inflating: dataset/test/authentic/Au_ani_0034.jpg  
  inflating: dataset/test/authentic/Au_ani_0035.jpg  
  inflating: dataset/test/authentic/Au_ani_0036.jpg  
  inflating: dataset/test/authentic/Au_ani_0037.jpg  
  inflating: dataset/test/authentic/Au_ani_0038.jpg  
  inflating: dataset/test/authentic/Au_ani_0039.jpg  
  inflating: dataset/test/authentic/Au_ani_0040.jpg  
  inflating: dataset/test/authentic/Au_ani_0041.jpg  
  inflating: dataset/test/

In [ ]:
!unzip /content/drive/MyDrive/test_filter.zip

importing required modules

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import cv2 as cv
import PIL
import tensorflow as tf
import keras as keras
from keras import layers
from keras.layers import Dense,Flatten
from keras.models import Sequential
from keras.optimizers.adam import Adam
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.utils import shuffle
from keras.callbacks import CSVLogger

collecting the data

In [ ]:
datagen=keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
train_path="/content/dataset/train"
test_path="/content/dataset/test"
nums=2560
nums2=200
train_data=datagen.flow_from_directory(
    train_path,
    batch_size=nums,
    class_mode="categorical",
    shuffle=True
)
test_data=datagen.flow_from_directory(
    test_path,
    batch_size=nums2,
    class_mode="categorical",
    shuffle=True
)

Found 2560 images belonging to 2 classes.
Found 200 images belonging to 2 classes.


Creating test data

In [ ]:
num=200
datagen=keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
bb5_30="/content/test_filter/bilatera_blur/bb5_30"
bb1=datagen.flow_from_directory(
    bb5_30,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
bb5_50="/content/test_filter/bilatera_blur/bb5_50"
bb2=datagen.flow_from_directory(
    bb5_50,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
bb5_100="/content/test_filter/bilatera_blur/bb5_100"
bb3=datagen.flow_from_directory(
    bb5_100,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
bb1_x,bb1_y=bb1.next()
keras.applications.resnet_v2.preprocess_input(
    bb1_x, data_format=None
)
bb2_x,bb2_y=bb2.next()
keras.applications.resnet_v2.preprocess_input(
    bb2_x, data_format=None
)
bb3_x,bb3_y=bb1.next()
keras.applications.resnet_v2.preprocess_input(
    bb3_x, data_format=None
)
Gb1="/content/test_filter/gaussian_blur/3_X_3"
gb1=datagen.flow_from_directory(
    Gb1,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
Gb2="/content/test_filter/gaussian_blur/5_X_5"
gb2=datagen.flow_from_directory(
    Gb2,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
gb1_x,gb1_y=bb2.next()
keras.applications.resnet_v2.preprocess_input(
    gb1_x, data_format=None
)
gb2_x,gb2_y=bb1.next()
keras.applications.resnet_v2.preprocess_input(
    gb2_x, data_format=None
)

Found 200 images belonging to 2 classes.
Found 200 images belonging to 2 classes.


array([[[[-0.99686277, -0.9964629 , -0.99600154],
         [-0.9967705 , -0.99633986, -0.99584776],
         [-0.9967705 , -0.99627835, -0.9957555 ],
         ...,
         [-0.9966474 , -0.9979392 , -0.9983391 ],
         [-0.99695504, -0.9982161 , -0.99867743],
         [-0.9973241 , -0.9984929 , -0.99895424]],

        [[-0.99695504, -0.9964629 , -0.9961553 ],
         [-0.99686277, -0.9964629 , -0.9960323 ],
         [-0.99701655, -0.99655515, -0.9960323 ],
         ...,
         [-0.9974779 , -0.9983699 , -0.99880046],
         [-0.99757016, -0.99852365, -0.99895424],
         [-0.99757016, -0.99852365, -0.99886197]],

        [[-0.9970473 , -0.9965859 , -0.9963091 ],
         [-0.9969858 , -0.9965244 , -0.9961553 ],
         [-0.9969243 , -0.99649364, -0.9960323 ],
         ...,
         [-0.9977547 , -0.99858516, -0.9988927 ],
         [-0.99778545, -0.99867743, -0.9988927 ],
         [-0.99784696, -0.9987082 , -0.99886197]],

        ...,

        [[-0.9930181 , -0.9931411 , -0

In [ ]:
WA_3="/content/test_filter/wieghted_average/WA3"
wa3=datagen.flow_from_directory(
    WA_3,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
WA_5="/content/test_filter/wieghted_average/WA5"
wa5=datagen.flow_from_directory(
    WA_5,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
wa3_x,wa3_y=wa3.next()
keras.applications.resnet_v2.preprocess_input(
    wa3_x, data_format=None
)
wa5_x,wa5_y=wa5.next()
keras.applications.resnet_v2.preprocess_input(
    wa5_x, data_format=None
)

Found 200 images belonging to 2 classes.
Found 200 images belonging to 2 classes.


array([[[[-0.9939715 , -0.993787  , -0.99391   ],
         [-0.99391   , -0.99375623, -0.99391   ],
         [-0.9940023 , -0.99381775, -0.9939715 ],
         ...,
         [-0.99347943, -0.99347943, -0.99347943],
         [-0.9934179 , -0.9934179 , -0.9933564 ],
         [-0.9933564 , -0.9933564 , -0.99326414]],

        [[-0.99440217, -0.99427915, -0.9940023 ],
         [-0.99434066, -0.99421763, -0.9939715 ],
         [-0.9943714 , -0.9942484 , -0.99409455],
         ...,
         [-0.9934179 , -0.99338716, -0.9933564 ],
         [-0.9935102 , -0.9935102 , -0.9933564 ],
         [-0.99338716, -0.99338716, -0.99326414]],

        [[-0.9941869 , -0.9940638 , -0.9938485 ],
         [-0.9941561 , -0.99403304, -0.99381775],
         [-0.9941561 , -0.99403304, -0.9938485 ],
         ...,
         [-0.99347943, -0.99347943, -0.99347943],
         [-0.99347943, -0.99347943, -0.99338716],
         [-0.9934487 , -0.9934487 , -0.9933564 ]],

        ...,

        [[-0.9943714 , -0.9947405 , -0

In [ ]:
KG_3="/content/test_filter/kuwahara/gaussian/3_X_3"
kg3=datagen.flow_from_directory(
    KG_3,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
kg3_x,kg3_y=kg3.next()
keras.applications.resnet_v2.preprocess_input(
    kg3_x, data_format=None
)
KG_5="/content/test_filter/kuwahara/gaussian/5_X_5"
kg5=datagen.flow_from_directory(
    KG_5,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
kg5_x,kg5_y=kg5.next()
keras.applications.resnet_v2.preprocess_input(
    kg5_x, data_format=None
)
KM_3="/content/test_filter/kuwahara/mean/3_X_3"
km3=datagen.flow_from_directory(
    KM_3,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
km3_x,km3_y=km3.next()
keras.applications.resnet_v2.preprocess_input(
    km3_x, data_format=None
)
KM_5="/content/test_filter/kuwahara/mean/5_X_5"
km5=datagen.flow_from_directory(
    KM_5,
    batch_size=num,
    class_mode="categorical",
    shuffle=True
)
km5_x,km5_y=km5.next()
keras.applications.resnet_v2.preprocess_input(
    km5_x, data_format=None
)

Found 200 images belonging to 2 classes.
Found 200 images belonging to 2 classes.
Found 200 images belonging to 2 classes.
Found 200 images belonging to 2 classes.


array([[[[-0.9995079 , -0.9988927 , -0.9996617 ],
         [-0.99947715, -0.99886197, -0.9995694 ],
         [-0.9993233 , -0.99880046, -0.9994464 ],
         ...,
         [-0.9979392 , -0.99695504, -0.9979085 ],
         [-0.9941561 , -0.9939715 , -0.994679  ],
         [-0.99387926, -0.993787  , -0.99421763]],

        [[-0.9993233 , -0.99873894, -0.99953866],
         [-0.9994464 , -0.9988312 , -0.9996002 ],
         [-0.99929255, -0.99880046, -0.99947715],
         ...,
         [-0.99784696, -0.99686277, -0.9978162 ],
         [-0.99510956, -0.994679  , -0.99538636],
         [-0.994925  , -0.99455595, -0.99504805]],

        [[-0.9993541 , -0.9987697 , -0.9995694 ],
         [-0.9993541 , -0.99873894, -0.99953866],
         [-0.9990465 , -0.9987697 , -0.9992618 ],
         ...,
         [-0.9974164 , -0.99649364, -0.9970473 ],
         [-0.9950788 , -0.99470973, -0.9953556 ],
         [-0.99489427, -0.99455595, -0.9950173 ]],

        ...,

        [[-0.99923104, -0.9987082 , -0

encoding the labels

In [ ]:
x_train,y_train=train_data.next()
x_test,y_test=test_data.next()
keras.applications.resnet_v2.preprocess_input(
    x_train, data_format=None
)
keras.applications.resnet_v2.preprocess_input(
    x_test, data_format=None
)

array([[[[-0.99421763, -0.99421763, -0.99427915],
         [-0.99412537, -0.99412537, -0.9941869 ],
         [-0.99409455, -0.99409455, -0.9941561 ],
         ...,
         [-0.99381775, -0.99381775, -0.99387926],
         [-0.9938485 , -0.9938485 , -0.99391   ],
         [-0.99403304, -0.99403304, -0.99409455]],

        [[-0.9942484 , -0.9942484 , -0.9943099 ],
         [-0.9941561 , -0.9941561 , -0.99421763],
         [-0.99409455, -0.99409455, -0.9941561 ],
         ...,
         [-0.993787  , -0.993787  , -0.9938485 ],
         [-0.9938485 , -0.9938485 , -0.99391   ],
         [-0.9940023 , -0.9940023 , -0.9940638 ]],

        [[-0.9943099 , -0.9943099 , -0.9943714 ],
         [-0.9941561 , -0.9941561 , -0.99421763],
         [-0.99409455, -0.99409455, -0.9941561 ],
         ...,
         [-0.993787  , -0.993787  , -0.9938485 ],
         [-0.99381775, -0.99381775, -0.99387926],
         [-0.9939715 , -0.9939715 , -0.99403304]],

        ...,

        [[-0.99421763, -0.9960938 , -0

the model

In [ ]:
resnet_model=Sequential()
pretrained_model=keras.applications.ResNet101V2(include_top=False,input_shape=(256,256,3),pooling="avg",weights="imagenet")
for layer in pretrained_model.layers:
    layer.trainable=True
resnet_model.add(pretrained_model)
resnet_model.add(Flatten())
resnet_model.add(Dense(1024,activation="relu"))
resnet_model.add(tf.keras.layers.BatchNormalization())
# resnet_model.add(tf.keras.layers.Dropout(0.4, noise_shape=None, seed=None))
resnet_model.add(Dense(512,activation="relu"))
resnet_model.add(tf.keras.layers.BatchNormalization())
resnet_model.add(tf.keras.layers.Dropout(0.4, noise_shape=None, seed=None))
resnet_model.add(Dense(2,activation="sigmoid"))
resnet_model.build(input_shape=(None,256,256,3))
print(resnet_model.summary())


171317808/171317808 [==============================] - 8s 0us/step
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet101v2 (Functional)    (None, 2048)              42626560  
                                                                 
 flatten (Flatten)           (None, 2048)              0         
                                                                 
 dense (Dense)               (None, 1024)              2098176   
                                                                 
 batch_normalization (BatchN  (None, 1024)             4096      
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 512)               524800    
                                                                 
 batch_normalization_1 (Batc  (None, 512)              

training the model

In [ ]:
resnet_model.compile(optimizer=Adam(learning_rate=0.0001),loss="binary_crossentropy",metrics=["accuracy"])
# Y=Y.toarray()
csv_logger = CSVLogger('training.csv')
resnet_model.fit(x=x_train,y=y_train,validation_split=0.07,batch_size=16,epochs=30,shuffle=True,verbose=2,callbacks=[csv_logger])
resnet_model.save_weights("model.h5")
# resnet_model.load_weights("/content/drive/MyDrive/resnet.h5")

Epoch 1/30
149/149 - 137s - loss: 0.4926 - accuracy: 0.8130 - val_loss: 0.7661 - val_accuracy: 0.4889 - 137s/epoch - 916ms/step
Epoch 2/30
149/149 - 51s - loss: 0.2653 - accuracy: 0.9118 - val_loss: 0.9899 - val_accuracy: 0.5111 - 51s/epoch - 340ms/step
Epoch 3/30
149/149 - 50s - loss: 0.1769 - accuracy: 0.9412 - val_loss: 1.6172 - val_accuracy: 0.5111 - 50s/epoch - 336ms/step
Epoch 4/30
149/149 - 50s - loss: 0.1336 - accuracy: 0.9517 - val_loss: 1.1036 - val_accuracy: 0.5944 - 50s/epoch - 338ms/step
Epoch 5/30
149/149 - 50s - loss: 0.1001 - accuracy: 0.9697 - val_loss: 1.9549 - val_accuracy: 0.5111 - 50s/epoch - 337ms/step
Epoch 6/30
149/149 - 50s - loss: 0.0916 - accuracy: 0.9702 - val_loss: 2.5578 - val_accuracy: 0.5167 - 50s/epoch - 337ms/step
Epoch 7/30
149/149 - 50s - loss: 0.0775 - accuracy: 0.9718 - val_loss: 2.0518 - val_accuracy: 0.4667 - 50s/epoch - 337ms/step
Epoch 8/30
149/149 - 50s - loss: 0.0884 - accuracy: 0.9693 - val_loss: 3.4727 - val_accuracy: 0.4778 - 50s/epoch - 3

testing the model

In [ ]:
pred=resnet_model.predict(x_test,batch_size=16,verbose=2)
score = resnet_model.evaluate(x_test,y_test, verbose = 2)
score = resnet_model.evaluate(bb1_x,bb1_y, verbose = 2)
score = resnet_model.evaluate(bb2_x,bb2_y, verbose = 2)
score = resnet_model.evaluate(bb3_x,bb3_y, verbose = 2)
score = resnet_model.evaluate(gb1_x,gb1_y, verbose = 2)
score = resnet_model.evaluate(gb2_x,gb2_y, verbose = 2)
score = resnet_model.evaluate(wa3_x,wa3_y, verbose = 2)
score = resnet_model.evaluate(wa5_x,wa5_y, verbose = 2)
score = resnet_model.evaluate(km3_x,km3_y, verbose = 2)
score = resnet_model.evaluate(km5_x,km5_y, verbose = 2)
score = resnet_model.evaluate(kg3_x,kg3_y, verbose = 2)
score = resnet_model.evaluate(kg5_x,kg5_y, verbose = 2)

plotting confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix
# pred2 =pred
import numpy as np
import seaborn as sns
y_test=np.argmax(y_test, axis=-1)
pred=np.argmax(pred,axis=-1)
# print(pred)
# print(test_labels)
labels1 = [0,1]
cm = confusion_matrix(y_test,pred,labels=labels1)
sns.heatmap(cm,
            annot=True,
            fmt='g',
            xticklabels=['forged','authentic'],
            yticklabels=['forged','authentic'])
# print(cm)
plt.ylabel('Prediction',fontsize=13)
plt.xlabel('Actual',fontsize=13)
plt.title('Confusion Matrix',fontsize=17)
plt.show()

In [ ]:
!cp "/content/model.h5" "/content/drive/MyDrive"